### ISSUE TITLE
初歩的なエラーでつまづいています

### ISSUE THREAD

**Issue by KijouShihona** [SpriteStudio/SSPlayerForGodot#13]
公式でSSPlayerForGodotを出していただきありがとうございます。
さっそく使ってみようと思い下記のリンクの説明の通りに進めているのですが、ビルド途中にエラーが起こってしまい進めません。
https://github.com/SpriteStudio/SSPlayerForGodot?tab=readme-ov-file#%E3%83%93%E3%83%AB%E3%83%89

Windows、Python 3.12.3、sconsは説明の通りにしてインストールと準備はできているはずですが

（画像消しました）
画像の通りエラーが出て完了できずにいます。

調べてみたのですが原因がわかりません。
個人ごとに環境が違うので難しいとは思うのですが、もしエラー原因に少しでも心当たりがあるようでしたら教えていただくことはできるでしょうか。

よろしくお願いします。

**Comment by Naruto** [comment]
README.md はビルド環境構築をオフィシャルドキュメントを前提にしておりまして、お手数ですが Godot オフィシャルドキュメントを参照にして Godot 単体をビルドできる環境にしていただいてよろしいでしょうか。

https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html

**Comment by SpriteStudio** [comment]
@KijouShihona 
該当箇所のエラーはPythonのエンコードがSJISになっているために起きるものと似ておりますので、試しに環境変数に PYTHONUTF8=1 を設定した状態でお試しいただけないでしょうか？

PYTHONUTF8 でWeb検索いただくと設定方法や、設定変更による影響など説明された記事が見つかりますので参考にしていただければと思います。

**Comment by KijouShihona** [comment]
丁寧なお返事をいただきありがとうございます。
お二人のアドバイスをいただき、行き詰まりにの先が見えるような気がしてきました。

参考にして試してみます。

**Comment by SpriteStudio** [comment]
@KijouShihona 
もし、環境変数にPYTHONUTF8=1 を加えることで別のビルド環境に問題が出るようでしたら、下記の手順を参考にされてください。   
https://github.com/SpriteStudio/SSPlayerForGodot#%E3%83%93%E3%83%AB%E3%83%89-1

**Comment by KijouShihona** [comment]
@SpriteStudio 
リンク先の手順でビルドに成功しました！
この手のことは素人ですのでとても助かりました。
ありがとうございます！
