### ISSUE TITLE
Godot v4 ではパーツカラーの表示が異なる

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SSPlayerForGodot#17]
# 状況

このIssueでは Godot v3 で動作していたもののうち v4 で動かない、もしくは変化したものに言及しています。  
最終的には SS 7 と同じ表示状態(末尾に添付)にできることが理想です。

- mix_whole: mulと同じように見える。
- add_whole: パーツカラー無しと同じように見える。
- mix_vertex: mul_vertex に近いが、ちょっと違う。
- add_vertex: add_whole 同様、色変化が無いように見える。

## 3
<img width="418" alt="parts_color_godot_v3" src="https://github.com/SpriteStudio/SSPlayerForGodot/assets/5088152/0d097a0b-150d-414f-9e94-7acfc5e2d459">

## 4.2.3.rc
<img width="418" alt="parts_color_gotod_v4_2" src="https://github.com/SpriteStudio/SSPlayerForGodot/assets/5088152/a10ca630-d63d-41b9-b88d-ec8990a13a0a">

## SS 7

<img width="418" alt="SS7" src="https://github.com/SpriteStudio/SSPlayerForGodot/assets/5088152/86a0bd03-19ce-41b1-9216-9965fc592963">

**Comment by Naruto** [comment]
#19

**Comment by MasamiYitsuse** [comment]
本症状はVer.1.1にて解消しました。  

▼対応バージョンへのリンク  
https://github.com/SpriteStudio/SSPlayerForGodot/tree/v1.1

▼比較スクリーンショット  
![SS_PartsColor_Compatibility](https://github.com/user-attachments/assets/08ac423c-76ae-4bbe-a667-78f7b08ab61f)
